name: Deploy API Documentation

on:
  push:
    branches:
      - deploy-doc

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml 4.13.x
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.13.x
          dune-cache: true
          opam-pin: false
          opam-depext: false

      - name: Pin packages
        run: |
          for f in *.opam; do
            opam pin add -yn "${f%.opam}" --dev-repo .
          done
        shell: bash

      - name: Install system dependencies
        run: |
          opam depext -y --with-doc $(ls -1 *.opam | sed -e 's/\.opam$//')
        shell: bash

      - name: Install OCaml dependencies
        run: opam install --deps-only -y --with-doc $(ls -1 *.opam | sed -e 's/\.opam$//')
        shell: bash

      - name: Deploy odoc to GitHub Pages
        uses: ocaml/setup-ocaml/deploy-doc@v2